version: '3'
services: 

    # API:
    #     build: 
    #         context: ./weeber_API
    #         dockerfile: dockerfile
    #     image: weeber_API:0.0.1
    #     container_name: weeber_API
    #     networks:
    #         my-network:
    #             aliases: 
    #                 - reverseproxy
    #     ports: 
    #         - 8000:5000

    weeber:
        build: 
            context: ../
            dockerfile: Dockerfile
        image: weeber:0.0.1
        container_name: weeber_web
        networks:
            default:
                ipv4_address: 192.168.0.3
        ports: 
            - 8001:5001
networks: 
    default:
        external:
            name: reverseproxy_nginx
