version: '3'
services: 
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - weeber
        networks:
            - my-network
        ports: 
            - 80:80

    # API:
    #     build: 
    #         context: ./weeber_API
    #         dockerfile: dockerfile
    #     image: weeber_API:0.0.1
    #     container_name: weeber_API
    #     networks:
    #         my-network:
    #             aliases: 
    #                 - reverseproxy
    #     ports: 
    #         - 8000:5000

    weeber:
        build: 
            context: ../
            dockerfile: Dockerfile
        image: weeber:0.0.1
        container_name: weeber
        networks:
            my-network:
                aliases: 
                    - reverseproxy
        ports: 
            - 8001:5001
networks: 
    my-network: